/**
 * @see https://theme-plume.vuejs.press/guide/collection/ 查看文档了解配置详情。
 *
 * Collections 配置文件，它在 `.vuepress/plume.config.ts` 中被导入。
 */

import { defineCollection, defineCollections } from 'vuepress-theme-plume'

/* =================== locale: zh-CN ======================= */

const zhGuideDoc = defineCollection({
  type: 'doc',
  dir: 'guide',
  linkPrefix: '/guide',
  title: '文档',
  sidebar: [
    {
      text: '从这里开始',
      icon: 'ri:book-open-line',
      prefix: '/guide/',
      collapsed: false,
      items: [
        { text: '介绍', link: 'intro/', icon: 'ri:information-line' },
        { text: '快速开始', link: 'get-started/', icon: 'ri:rocket-line', badge: { type: 'tip', text: '起步' } },
        { text: '项目结构', link: 'project-structure/', icon: 'ri:node-tree', badge: { type: 'info', text: '架构' } },
        {
          text: '部署',
          icon: 'ri:cloud-line',
          prefix: '/guide/deploy/',
          collapsed: true,
          items: [
            { text: 'Vercel', link: 'vercel/', icon: 'ri:vercel-line', badge: { type: 'tip', text: '推荐' } },
            { text: 'Netlify', link: 'netlify/', icon: 'ri:cloud-line' },
            { text: 'GitHub Pages', link: 'github/', icon: 'ri:github-line', badge: { type: 'danger', text: '不推荐' } },
            { text: 'Cloudflare Pages', link: 'cloudflare/', icon: 'ri:cloud-line' },
            { text: 'EdgeOne Pages', link: 'edgeone/', icon: 'ri:cloud-line', badge: { type: 'tip', text: '推荐' } },
            { text: '服务器部署', link: 'server/', icon: 'ri:server-line', badge: { type: 'info', text: '入门' } },
            { text: 'Docker 部署', link: 'docker/', icon: 'ri:ship-line' },
            { text: '本地构建', link: 'local/', icon: 'ri:computer-line', badge: { type: 'info', text: '入门' } },
          ],
        },
        { text: 'Frontmatter', link: 'frontmatter/', icon: 'ri:file-list-3-line', badge: { type: 'warning', text: '规范' } },
        { text: '编写文章', link: 'writing-post/', icon: 'ri:quill-pen-line' },
        { text: '构建优化', link: 'optimize-build/', icon: 'ri:speed-up-line', badge: { type: 'tip', text: '优化' } },
      ],
    },
    {
      text: '内容分离',
      icon: 'ri:git-branch-line',
      prefix: '/guide/content-separation/',
      collapsed: true,
      items: [
        { text: '架构概览', link: 'concepts/', icon: 'ri:information-line', badge: { type: 'tip', text: '核心' } },
        { text: '初始化私有仓库', link: 'init-repo/', icon: 'ri:folder-add-line' },
        { text: '本地预览与调试', link: 'local-preview/', icon: 'ri:computer-line' },
        { text: 'CLI 工具链', link: 'cli-workflows/', icon: 'ri:terminal-box-line', badge: { type: 'info', text: 'CLI' } },
        { text: '配置覆盖原理', link: 'config-overlay/', icon: 'ri:settings-3-line', badge: { type: 'warning', text: '原理' } },
        { text: '跨仓自动构建', link: 'ci-dispatch/', icon: 'ri:cloud-line', badge: { type: 'tip', text: '推荐' } },
        { text: '托管平台部署钩子', link: 'deploy-hooks/', icon: 'ri:link-m' },
        { text: '常见问题与排错', link: 'faq/', icon: 'ri:question-line' },
      ],
    },
    {
      text: '基础布局',
      icon: 'ri:layout-2-line',
      prefix: '/guide/layout/',
      collapsed: true,
      items: [
        { text: '基础配置', link: 'site-config/', icon: 'ri:settings-3-line' },
        { text: '动态配色', link: 'theme-color/', icon: 'ri:palette-line', badge: { type: 'warning', text: '核心' } },
        { text: '横幅与背景', link: 'banner/', icon: 'ri:image-line' },
        { text: '导航栏配置', link: 'navbar/', icon: 'ri:menu-line' },
        { text: '侧栏布局', link: 'sidebar/', icon: 'ri:sidebar-unfold-line' },
        { text: '页脚与博主资料', link: 'footer-profile/', icon: 'ri:user-smile-line' },
        { text: '自定义字体', link: 'font/', icon: 'ri:font-size-2' },
      ],
    },
    {
      text: '文章布局',
      icon: 'ri:file-text-line',
      prefix: '/guide/article/',
      collapsed: true,
      items: [
        { text: '文章页配置', link: 'article-config/', icon: 'ri:article-line' },
        { text: '悬浮控制流', link: 'fab/', icon: 'ri:cursor-line', badge: { type: 'info', text: 'FAB' } },
        { text: '版权声明', link: 'copyright/', icon: 'ri:copyright-line' },
        { text: '评论系统', link: 'comments/', icon: 'ri:message-3-line', badge: { type: 'tip', text: 'Twikoo' } },
        { text: '代码块主题', link: 'code-theme/', icon: 'ri:code-line' },
      ],
    },
    {
      text: '页面配置',
      icon: 'ri:star-line',
      prefix: '/guide/pages/',
      collapsed: true,
      items: [
        { text: '独立页面总览', link: 'pages-overview/', icon: 'ri:apps-line' },
        { text: '关于页', link: 'about/', icon: 'ri:user-line' },
        { text: '瞬间页', link: 'moments/', icon: 'ri:bubble-chart-line' },
        { text: '友链页', link: 'friends/', icon: 'ri:links-line' },
        { text: '项目页', link: 'projects/', icon: 'ri:rocket-line' },
        { text: '技能页', link: 'skills/', icon: 'ri:lightbulb-line' },
        { text: '设备页', link: 'devices/', icon: 'ri:computer-line' },
        { text: '时间线页', link: 'timeline/', icon: 'ri:time-line' },
        { text: '番剧页', link: 'anime/', icon: 'ri:tv-line', badge: { type: 'tip', text: '追番' } },
      ],
    },
    {
      text: '侧边栏组件',
      icon: 'ri:window-line',
      prefix: '/guide/widgets/',
      collapsed: true,
      items: [
        { text: '组件总览', link: 'widgets-overview/', icon: 'ri:layout-grid-line' },
        { text: '公告组件', link: 'announcement/', icon: 'ri:notification-3-line' },
        { text: '音乐播放器', link: 'music/', icon: 'ri:music-2-line', badge: { type: 'tip', text: '推荐' } },
        { text: '基础组件', link: 'basic-widgets/', icon: 'ri:stack-line' },
      ],
    },
    {
      text: '特色功能',
      icon: 'ri:magic-line',
      prefix: '/guide/features/',
      collapsed: true,
      items: [
        { text: '右键增强菜单', link: 'context-menu/', icon: 'ri:cursor-line', badge: { type: 'tip', text: '新' } },
        { text: '图片色调辉光', link: 'image-bloom/', icon: 'ri:blur-off-line', badge: { type: 'tip', text: '视觉' } },
        { text: 'Umami 统计', link: 'umami/', icon: 'ri:bar-chart-2-line', badge: { type: 'info', text: '分析' } },
        { text: '订阅与机器可读输出', link: 'feeds/', icon: 'ri:rss-line', badge: { type: 'info', text: '输出' } },
        { text: 'LLM 友好内容', link: 'llms/', icon: 'ri:robot-line', badge: { type: 'tip', text: 'AI' } },
      ],
    },
    {
      text: 'API',
      icon: 'ri:code-s-slash-line',
      prefix: '/guide/api/',
      collapsed: true,
      items: [
        {
          text: '用户',
          icon: 'ri:user-line',
          prefix: 'user/',
          collapsed: true,
          items: [
            { text: 'Meting API', link: 'meting/', icon: 'ri:music-2-line', badge: { type: 'info', text: '音乐' } },
            { text: 'Bangumi API', link: 'bangumi/', icon: 'ri:film-line', badge: { type: 'tip', text: '番剧' } },
            { text: 'Bilibili API', link: 'bilibili/', icon: 'ri:bilibili-line', badge: { type: 'tip', text: '同步' } },
            { text: 'Umami API', link: 'umami/', icon: 'ri:bar-chart-2-line', badge: { type: 'info', text: '统计' } },
          ],
        },
        {
          text: '组件',
          icon: 'ri:apps-line',
          prefix: 'components/',
          collapsed: true,
          items: [
            { text: '设计规范与契约', link: 'overview/', icon: 'ri:book-read-line', badge: { type: 'warning', text: '核心' } },
            { text: '操作交互原子', link: 'actions/', icon: 'ri:cursor-line', badge: { type: 'info', text: 'M3E' } },
            { text: '输入与选择原子', link: 'inputs/', icon: 'ri:edit-box-line' },
            { text: '展示与反馈原子', link: 'display/', icon: 'ri:layout-grid-line' },
            { text: '导航与浮层原子', link: 'overlay-nav/', icon: 'ri:window-line' },
            { text: '博客专用原子', link: 'blog-atoms/', icon: 'ri:quill-pen-line', badge: { type: 'tip', text: 'SSR' } },
            { text: '业务实体与页面模块', link: 'organisms/', icon: 'ri:pages-line', badge: { type: 'info', text: '模块' } },
            { text: '全局外壳与侧栏部件', link: 'shell-widgets/', icon: 'ri:dashboard-line', badge: { type: 'info', text: 'Shell' } },
          ],
        },
      ],
    },
    {
      text: '常见问题',
      icon: 'ri:question-line',
      prefix: '/guide/faq/',
      collapsed: true,
      items: [
        { text: '错误排查', link: 'troubleshooting/', icon: 'ri:bug-line', badge: { type: 'danger', text: '必看' } },
        { text: '提问与反馈', link: 'asking-questions/', icon: 'ri:chat-smile-2-line' },
      ],
    },
    {
      text: '写作',
      icon: 'ri:quill-pen-line',
      prefix: '/guide/writing/',
      collapsed: true,
      items: [
        {
          text: 'markdown',
          icon: 'ri:markdown-line',
          prefix: 'markdown/',
          collapsed: true,
          items: [
            { text: '基础语法', link: 'basic/', icon: 'ri:text' },
            { text: '扩展与属性', link: 'attributes/', icon: 'ri:code-s-line' },
            { text: '原生表情与图标', link: 'emoji-icons/', icon: 'ri:emotion-line' },
            { text: '数学公式', link: 'math/', icon: 'ri:functions' },
            { text: '响应式表格', link: 'table/', icon: 'ri:table-line', badge: { type: 'tip', text: '新' } },
            { text: '马克笔高亮', link: 'marker/', icon: 'ri:mark-pen-line' },
            { text: '隐秘文本', link: 'spoiler/', icon: 'ri:eye-close-line', badge: { type: 'tip', text: '防剧透' } },
            { text: '缩写词悬浮', link: 'abbreviations/', icon: 'ri:chat-quote-line' },
            { text: '内容注释', link: 'annotations/', icon: 'ri:chat-new-line' },
            { text: '提示容器', link: 'admonitions/', icon: 'ri:notification-line' },
            { text: 'Github 警报', link: 'github-alerts/', icon: 'ri:alarm-warning-line' },
            { text: '卡片与字段组', link: 'cards/', icon: 'ri:id-card-line' },
            { text: '步骤引导', link: 'steps/', icon: 'ri:list-ordered' },
            { text: '文件树', link: 'file-tree/', icon: 'ri:node-tree' },
            { text: '代码树', link: 'code-tree/', icon: 'ri:file-code-line', badge: { type: 'tip', text: '新' } },
            { text: '代码选项组', link: 'tabs/', icon: 'material-symbols:tab-outline-rounded', badge: { type: 'tip', text: '新' } },
            { text: '图片画廊与排版', link: 'image-grid/', icon: 'ri:image-line', badge: { type: 'tip', text: '画廊' } },
            { text: '文件片段导入', link: 'include/', icon: 'ri:file-copy-2-line' },
          ],
        },
        {
          text: '组织',
          icon: 'ri:folder-settings-line',
          prefix: 'organization/',
          collapsed: true,
          items: [
            { text: '单文件方案', link: 'file/', icon: 'ri:file-text-line' },
            { text: '文件夹方案', link: 'folder/', icon: 'ri:folder-line', badge: { type: 'tip', text: '推荐' } },
          ],
        },
        {
          text: '高级',
          icon: 'ri:settings-3-line',
          prefix: 'advanced/',
          collapsed: true,
          items: [
            { text: '固定链接', link: 'permalink/', icon: 'ri:link-m' },
            { text: '加密(可选)', link: 'encryption/', icon: 'ri:key-line', badge: { type: 'info', text: '可选' } },
          ],
        },
        {
          text: '代码块',
          icon: 'ri:code-box-line',
          prefix: 'codeblock/',
          collapsed: true,
          items: [
            { text: '语法高亮与行号', link: 'highlight/', icon: 'ri:code-line' },
            { text: '标题与文件名', link: 'titles/', icon: 'ri:file-text-line' },
            { text: '高亮与差异标记', link: 'diff/', icon: 'ri:focus-mode' },
            { text: '代码折叠与复制', link: 'collapse/', icon: 'ri:file-copy-line' },
            { text: '代码选项组', link: 'tabs/', icon: 'material-symbols:tab-outline-rounded' },
          ],
        },
        {
          text: '图表',
          icon: 'ri:line-chart-line',
          prefix: 'charts/',
          collapsed: true,
          items: [
            { text: 'Mermaid 图表', link: 'mermaid/', icon: 'ri:node-tree' },
          ],
        },
        {
          text: '资源嵌入',
          icon: 'ri:video-line',
          prefix: 'media/',
          collapsed: true,
          items: [
            { text: 'Bilibili 视频', link: 'bilibili/', icon: 'ri:bilibili-line' },
            { text: 'YouTube 视频', link: 'youtube/', icon: 'ri:youtube-line' },
            { text: 'AcFun 视频', link: 'acfun/', icon: 'ri:video-line' },
            { text: 'ArtPlayer 播放器', link: 'artplayer/', icon: 'ri:play-line', badge: { type: 'tip', text: '推荐' } },
            { text: '音频朗读条', link: 'audio/', icon: 'ri:voiceprint-line', badge: { type: 'info', text: 'TTS' } },
          ],
        },
      ],
    },
  ].sort((left, right) => {
    const order = [
      '/guide/',
      '/guide/content-separation/',
      '/guide/layout/',
      '/guide/article/',
      '/guide/writing/',
      '/guide/pages/',
      '/guide/widgets/',
      '/guide/features/',
      '/guide/api/',
      '/guide/faq/',
    ]

    return order.indexOf(left.prefix) - order.indexOf(right.prefix)
  }),
})

export const zhCollections = defineCollections([
  zhGuideDoc,
])

/* =================== locale: en-US ======================= */

const enGuideDoc = defineCollection({
  type: 'doc',
  dir: 'guide',
  linkPrefix: '/guide',
  title: 'Documentation',
  sidebar: [
    {
      text: 'Getting Started',
      icon: 'ri:book-open-line',
      prefix: '/en/guide/',
      collapsed: false,
      items: [
        { text: 'Introduction', link: 'intro/', icon: 'ri:information-line' },
        { text: 'Quick Start', link: 'get-started/', icon: 'ri:rocket-line', badge: { type: 'tip', text: 'Start' } },
        { text: 'Project Structure', link: 'project-structure/', icon: 'ri:node-tree', badge: { type: 'info', text: 'Structure' } },
        {
          text: 'Deployment',
          icon: 'ri:cloud-line',
          prefix: '/en/guide/deploy/',
          collapsed: true,
          items: [
            { text: 'Vercel', link: 'vercel/', icon: 'ri:vercel-line', badge: { type: 'tip', text: 'Recommended' } },
            { text: 'Netlify', link: 'netlify/', icon: 'ri:cloud-line' },
            { text: 'GitHub Pages', link: 'github/', icon: 'ri:github-line', badge: { type: 'danger', text: 'Not Recommended' } },
            { text: 'Cloudflare Pages', link: 'cloudflare/', icon: 'ri:cloud-line' },
            { text: 'EdgeOne Pages', link: 'edgeone/', icon: 'ri:cloud-line', badge: { type: 'tip', text: 'Recommended' } },
            { text: 'Server Deployment', link: 'server/', icon: 'ri:server-line', badge: { type: 'info', text: 'Basic' } },
            { text: 'Docker Deployment', link: 'docker/', icon: 'ri:ship-line' },
            { text: 'Local Build', link: 'local/', icon: 'ri:computer-line', badge: { type: 'info', text: 'Basic' } },
          ],
        },
        { text: 'Frontmatter', link: 'frontmatter/', icon: 'ri:file-list-3-line', badge: { type: 'warning', text: 'Config' } },
        { text: 'Writing Posts', link: 'writing-post/', icon: 'ri:quill-pen-line' },
        { text: 'Build Optimization', link: 'optimize-build/', icon: 'ri:speed-up-line', badge: { type: 'tip', text: 'Optimize' } },
      ],
    },
    {
      text: 'Content Separation',
      icon: 'ri:git-branch-line',
      prefix: '/en/guide/content-separation/',
      collapsed: true,
      items: [
        { text: 'Architecture Overview', link: 'concepts/', icon: 'ri:information-line', badge: { type: 'tip', text: 'Core' } },
        { text: 'Initialize Private Repo', link: 'init-repo/', icon: 'ri:folder-add-line' },
        { text: 'Local Preview & Debugging', link: 'local-preview/', icon: 'ri:computer-line' },
        { text: 'CLI Toolchain', link: 'cli-workflows/', icon: 'ri:terminal-box-line', badge: { type: 'info', text: 'CLI' } },
        { text: 'Configuration Overlay', link: 'config-overlay/', icon: 'ri:settings-3-line', badge: { type: 'warning', text: 'Overlay' } },
        { text: 'Cross-Repo CI Dispatch', link: 'ci-dispatch/', icon: 'ri:cloud-line', badge: { type: 'tip', text: 'Recommended' } },
        { text: 'Hosting Deploy Hooks', link: 'deploy-hooks/', icon: 'ri:link-m' },
        { text: 'Troubleshooting & FAQ', link: 'faq/', icon: 'ri:question-line' },
      ],
    },
    {
      text: 'Basic Layout',
      icon: 'ri:layout-2-line',
      prefix: '/en/guide/layout/',
      collapsed: true,
      items: [
        { text: 'Site Config', link: 'site-config/', icon: 'ri:settings-3-line' },
        { text: 'Dynamic Color', link: 'theme-color/', icon: 'ri:palette-line', badge: { type: 'warning', text: 'Core' } },
        { text: 'Banner & Background', link: 'banner/', icon: 'ri:image-line' },
        { text: 'Navbar Config', link: 'navbar/', icon: 'ri:menu-line' },
        { text: 'Sidebar Layout', link: 'sidebar/', icon: 'ri:sidebar-unfold-line' },
        { text: 'Footer & Profile', link: 'footer-profile/', icon: 'ri:user-smile-line' },
        { text: 'Custom Fonts', link: 'font/', icon: 'ri:font-size-2' },
      ],
    },
    {
      text: 'Article Layout',
      icon: 'ri:file-text-line',
      prefix: '/en/guide/article/',
      collapsed: true,
      items: [
        { text: 'Article Page Config', link: 'article-config/', icon: 'ri:article-line' },
        { text: 'Floating Controls (FAB)', link: 'fab/', icon: 'ri:cursor-line', badge: { type: 'info', text: 'FAB' } },
        { text: 'Copyright Notice', link: 'copyright/', icon: 'ri:copyright-line' },
        { text: 'Comment System', link: 'comments/', icon: 'ri:message-3-line', badge: { type: 'tip', text: 'Twikoo' } },
        { text: 'Code Block Themes', link: 'code-theme/', icon: 'ri:code-line' },
      ],
    },
    {
      text: 'Page Configurations',
      icon: 'ri:star-line',
      prefix: '/en/guide/pages/',
      collapsed: true,
      items: [
        { text: 'Standalone Pages Overview', link: 'pages-overview/', icon: 'ri:apps-line' },
        { text: 'About Page', link: 'about/', icon: 'ri:user-line' },
        { text: 'Moments', link: 'moments/', icon: 'ri:bubble-chart-line' },
        { text: 'Friends Page', link: 'friends/', icon: 'ri:links-line' },
        { text: 'Projects', link: 'projects/', icon: 'ri:rocket-line' },
        { text: 'Skills', link: 'skills/', icon: 'ri:lightbulb-line' },
        { text: 'Devices', link: 'devices/', icon: 'ri:computer-line' },
        { text: 'Timeline', link: 'timeline/', icon: 'ri:time-line' },
        { text: 'Anime Page', link: 'anime/', icon: 'ri:tv-line', badge: { type: 'tip', text: 'Anime' } },
      ],
    },
    {
      text: 'Sidebar Widgets',
      icon: 'ri:window-line',
      prefix: '/en/guide/widgets/',
      collapsed: true,
      items: [
        { text: 'Widgets Overview', link: 'widgets-overview/', icon: 'ri:layout-grid-line' },
        { text: 'Announcement', link: 'announcement/', icon: 'ri:notification-3-line' },
        { text: 'Music Player', link: 'music/', icon: 'ri:music-2-line', badge: { type: 'tip', text: 'Recommended' } },
        { text: 'Basic Widgets', link: 'basic-widgets/', icon: 'ri:stack-line' },
      ],
    },
    {
      text: 'Special Features',
      icon: 'ri:magic-line',
      prefix: '/en/guide/features/',
      collapsed: true,
      items: [
        { text: 'Context Menu', link: 'context-menu/', icon: 'ri:cursor-line', badge: { type: 'tip', text: 'New' } },
        { text: 'Image Tonal Bloom', link: 'image-bloom/', icon: 'ri:blur-off-line', badge: { type: 'tip', text: 'Visual' } },
        { text: 'Umami Analytics', link: 'umami/', icon: 'ri:bar-chart-2-line', badge: { type: 'info', text: 'Analytics' } },
        { text: 'Feeds & Machine-Readable Output', link: 'feeds/', icon: 'ri:rss-line', badge: { type: 'info', text: 'Output' } },
        { text: 'LLM-Friendly Content', link: 'llms/', icon: 'ri:robot-line', badge: { type: 'tip', text: 'AI' } },
      ],
    },
    {
      text: 'API',
      icon: 'ri:code-s-slash-line',
      prefix: '/en/guide/api/',
      collapsed: true,
      items: [
        {
          text: 'User',
          icon: 'ri:user-line',
          prefix: 'user/',
          collapsed: true,
          items: [
            { text: 'Meting API', link: 'meting/', icon: 'ri:music-2-line', badge: { type: 'info', text: 'Music' } },
            { text: 'Bangumi API', link: 'bangumi/', icon: 'ri:film-line', badge: { type: 'tip', text: 'Anime' } },
            { text: 'Bilibili API', link: 'bilibili/', icon: 'ri:bilibili-line', badge: { type: 'tip', text: 'Sync' } },
            { text: 'Umami API', link: 'umami/', icon: 'ri:bar-chart-2-line', badge: { type: 'info', text: 'Stats' } },
          ],
        },
        {
          text: 'Components',
          icon: 'ri:apps-line',
          prefix: 'components/',
          collapsed: true,
          items: [
            { text: 'Design Contract', link: 'overview/', icon: 'ri:book-read-line', badge: { type: 'warning', text: 'Core' } },
            { text: 'Action Atoms', link: 'actions/', icon: 'ri:cursor-line', badge: { type: 'info', text: 'M3E' } },
            { text: 'Input & Selection', link: 'inputs/', icon: 'ri:edit-box-line' },
            { text: 'Display & Feedback', link: 'display/', icon: 'ri:layout-grid-line' },
            { text: 'Navigation & Overlay', link: 'overlay-nav/', icon: 'ri:window-line' },
            { text: 'Blog-Specific Atoms', link: 'blog-atoms/', icon: 'ri:quill-pen-line', badge: { type: 'tip', text: 'SSR' } },
            { text: 'Organisms & Sections', link: 'organisms/', icon: 'ri:pages-line', badge: { type: 'info', text: 'Organism' } },
            { text: 'Shell & Widgets', link: 'shell-widgets/', icon: 'ri:dashboard-line', badge: { type: 'info', text: 'Shell' } },
          ],
        },
      ],
    },
    {
      text: 'FAQ',
      icon: 'ri:question-line',
      prefix: '/en/guide/faq/',
      collapsed: true,
      items: [
        { text: 'Troubleshooting', link: 'troubleshooting/', icon: 'ri:bug-line', badge: { type: 'danger', text: 'Must-Read' } },
        { text: 'Asking & Feedback', link: 'asking-questions/', icon: 'ri:chat-smile-2-line' },
      ],
    },
    {
      text: 'Writing',
      icon: 'ri:quill-pen-line',
      prefix: '/en/guide/writing/',
      collapsed: true,
      items: [
        {
          text: 'Markdown',
          icon: 'ri:markdown-line',
          prefix: 'markdown/',
          collapsed: true,
          items: [
            { text: 'Basic Syntax', link: 'basic/', icon: 'ri:text' },
            { text: 'Attributes & Directives', link: 'attributes/', icon: 'ri:code-s-line' },
            { text: 'Emojis & Icons', link: 'emoji-icons/', icon: 'ri:emotion-line' },
            { text: 'Math & Formulas', link: 'math/', icon: 'ri:functions' },
            { text: 'Responsive Tables', link: 'table/', icon: 'ri:table-line', badge: { type: 'tip', text: 'New' } },
            { text: 'Marker Highlights', link: 'marker/', icon: 'ri:mark-pen-line' },
            { text: 'Inline Spoiler', link: 'spoiler/', icon: 'ri:eye-close-line', badge: { type: 'tip', text: 'Spoiler' } },
            { text: 'Abbreviations', link: 'abbreviations/', icon: 'ri:chat-quote-line' },
            { text: 'Content Annotations', link: 'annotations/', icon: 'ri:chat-new-line' },
            { text: 'Admonition Containers', link: 'admonitions/', icon: 'ri:notification-line' },
            { text: 'GitHub Alerts', link: 'github-alerts/', icon: 'ri:alarm-warning-line' },
            { text: 'Cards & Fields', link: 'cards/', icon: 'ri:id-card-line' },
            { text: 'Step Guides', link: 'steps/', icon: 'ri:list-ordered' },
            { text: 'File Tree', link: 'file-tree/', icon: 'ri:node-tree' },
            { text: 'Code Tree', link: 'code-tree/', icon: 'ri:file-code-line', badge: { type: 'tip', text: 'New' } },
            { text: 'Code Tabs', link: 'tabs/', icon: 'material-symbols:tab-outline-rounded', badge: { type: 'tip', text: 'New' } },
            { text: 'Image Grid & Media', link: 'image-grid/', icon: 'ri:image-line', badge: { type: 'tip', text: 'Gallery' } },
            { text: 'File Include', link: 'include/', icon: 'ri:file-copy-2-line' },
          ],
        },
        {
          text: 'Organization',
          icon: 'ri:folder-settings-line',
          prefix: 'organization/',
          collapsed: true,
          items: [
            { text: 'Single File Mode', link: 'file/', icon: 'ri:file-text-line' },
            { text: 'Folder Mode', link: 'folder/', icon: 'ri:folder-line', badge: { type: 'tip', text: 'Recommended' } },
          ],
        },
        {
          text: 'Advanced',
          icon: 'ri:settings-3-line',
          prefix: 'advanced/',
          collapsed: true,
          items: [
            { text: 'Permalinks', link: 'permalink/', icon: 'ri:link-m' },
            { text: 'Encryption (Optional)', link: 'encryption/', icon: 'ri:key-line', badge: { type: 'info', text: 'Optional' } },
          ],
        },
        {
          text: 'Code Blocks',
          icon: 'ri:code-box-line',
          prefix: 'codeblock/',
          collapsed: true,
          items: [
            { text: 'Syntax Highlighting', link: 'highlight/', icon: 'ri:code-line' },
            { text: 'Titles & File Names', link: 'titles/', icon: 'ri:file-text-line' },
            { text: 'Highlights & Diffs', link: 'diff/', icon: 'ri:focus-mode' },
            { text: 'Collapsing & Copying', link: 'collapse/', icon: 'ri:file-copy-line' },
            { text: 'Code Tabs', link: 'tabs/', icon: 'material-symbols:tab-outline-rounded' },
          ],
        },
        {
          text: 'Charts',
          icon: 'ri:line-chart-line',
          prefix: 'charts/',
          collapsed: true,
          items: [
            { text: 'Mermaid Diagrams', link: 'mermaid/', icon: 'ri:node-tree' },
          ],
        },
        {
          text: 'Media Embeds',
          icon: 'ri:video-line',
          prefix: 'media/',
          collapsed: true,
          items: [
            { text: 'Bilibili Video', link: 'bilibili/', icon: 'ri:bilibili-line' },
            { text: 'YouTube Video', link: 'youtube/', icon: 'ri:youtube-line' },
            { text: 'AcFun Video', link: 'acfun/', icon: 'ri:video-line' },
            { text: 'ArtPlayer Player', link: 'artplayer/', icon: 'ri:play-line', badge: { type: 'tip', text: 'Recommended' } },
            { text: 'Audio Reader', link: 'audio/', icon: 'ri:voiceprint-line', badge: { type: 'info', text: 'TTS' } },
          ],
        },
      ],
    },
  ].sort((left, right) => {
    const order = [
      '/en/guide/',
      '/en/guide/content-separation/',
      '/en/guide/layout/',
      '/en/guide/article/',
      '/en/guide/writing/',
      '/en/guide/pages/',
      '/en/guide/widgets/',
      '/en/guide/features/',
      '/en/guide/api/',
      '/en/guide/faq/',
    ]

    return order.indexOf(left.prefix) - order.indexOf(right.prefix)
  }),
})

export const enCollections = defineCollections([
  enGuideDoc,
])
